[package]
name = "lufloat"
version = "0.1.9"
edition = "2024"
description = "Fastest FP16 Math and AI Library for AMD APUs"
license = "AGPL-3.0-only"
repository = "https://github.com/Legendofzaday/lufloat"
readme = "README.md"
keywords = ["gpu", "math", "f16", "rocm", "hip"]
categories = ["concurrency", "graphics", "hardware-support", "mathematics", "memory-management"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
