name: Rust

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cargo fmt --all
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "style: auto-format rust files"
